version: 0.0
os: linux
files:
 - source: /circle/vars.env
   destination: /home/ubuntu/beblue-api-gateway
 - source: /circle/stage/beblue-api-gateway.yml
   destination: /home/ubuntu/beblue-api-gateway/stage
 - source: /circle/prod/beblue-api-gateway.yml
   destination: /home/ubuntu/beblue-api-gateway/prod

permissions:
 - object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
 BeforeInstall:
   - location: circle/scripts/codedeploy-agent.sh
     timeout: 30
     runas: root
 ApplicationStart:
   - location: circle/scripts/update-stack.sh
     timeout : 60
     runas: root
 ValidateService:
   - location: circle/scripts/test-app.sh
     timeout: 100
     runas: root